-- =========================================================

SET NAMES 'utf8mb4';
SET CHARACTER SET utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE inscripciones;
TRUNCATE TABLE matriculas;
TRUNCATE TABLE materias;
TRUNCATE TABLE docentes;
TRUNCATE TABLE alumnos;
SET FOREIGN_KEY_CHECKS = 1;

-- 1. POBLAMIENTO DE LA TABLA: alumnos (100 registros)
-- Mezcla multicultural: Japonés, Americano, Europeo, Latino
INSERT INTO alumnos (id, idAlumno, codigo, nombre, direccion, email, telefono, created_at, updated_at) VALUES
(1, UUID(), 'ALU001', 'Kenji Sato', 'Shinjuku-ku, Tokyo, JP', 'kenji.sato@example.com', '7001-1001', NOW(), NOW()),
(2, UUID(), 'ALU002', 'Emily Johnson', 'High St, London, UK', 'emily.johnson@example.com', '7001-1002', NOW(), NOW()),
(3, UUID(), 'ALU003', 'Hans Müller', 'Berlin, Germany', 'hans.mueller@example.com', '7001-1003', NOW(), NOW()),
(4, UUID(), 'ALU004', 'Carlos Rodríguez', 'San Salvador, SV', 'carlos.rodriguez@example.com', '7001-1004', NOW(), NOW()),
(5, UUID(), 'ALU005', 'Yuki Tanaka', 'Osaka, JP', 'yuki.tanaka@example.com', '7001-1005', NOW(), NOW()),
(6, UUID(), 'ALU006', 'James Smith', 'New York, US', 'james.smith@example.com', '7001-1006', NOW(), NOW()),
(7, UUID(), 'ALU007', 'Claire Dubois', 'Paris, France', 'claire.dubois@example.com', '7001-1007', NOW(), NOW()),
(8, UUID(), 'ALU008', 'Maria García', 'Madrid, Spain', 'maria.garcia@example.com', '7001-1008', NOW(), NOW()),
(9, UUID(), 'ALU009', 'Hikaru Aoki', 'Kyoto, JP', 'hikaru.aoki@example.com', '7001-1009', NOW(), NOW()),
(10, UUID(), 'ALU010', 'Robert Brown', 'Chicago, US', 'robert.brown@example.com', '7001-1010', NOW(), NOW()),
(11, UUID(), 'ALU011', 'Lukas Schneider', 'Munich, Germany', 'lukas.schneider@example.com', '7001-1011', NOW(), NOW()),
(12, UUID(), 'ALU012', 'Ana Martínez', 'CDMX, Mexico', 'ana.martinez@example.com', '7001-1012', NOW(), NOW()),
(13, UUID(), 'ALU013', 'Akira Yamamoto', 'Yokohama, JP', 'akira.yamamoto@example.com', '7001-1013', NOW(), NOW()),
(14, UUID(), 'ALU014', 'Sarah Williams', 'San Francisco, US', 'sarah.williams@example.com', '7001-1014', NOW(), NOW()),
(15, UUID(), 'ALU015', 'Pierre Leroy', 'Marseille, France', 'pierre.leroy@example.com', '7001-1015', NOW(), NOW()),
(16, UUID(), 'ALU016', 'Jorge Hernández', 'Bogotá, Colombia', 'jorge.hernandez@example.com', '7001-1016', NOW(), NOW()),
(17, UUID(), 'ALU017', 'Haruto Itō', 'Nagoya, JP', 'haruto.ito@example.com', '7001-1017', NOW(), NOW()),
(18, UUID(), 'ALU018', 'Jennifer Miller', 'Boston, US', 'jennifer.miller@example.com', '7001-1018', NOW(), NOW()),
(19, UUID(), 'ALU019', 'Stefan Wagner', 'Hamburg, Germany', 'stefan.wagner@example.com', '7001-1019', NOW(), NOW()),
(20, UUID(), 'ALU020', 'Luis Castro', 'Lima, Peru', 'luis.castro@example.com', '7001-1020', NOW(), NOW()),
(21, UUID(), 'ALU021', 'Kaito Nakamura', 'Sapporo, JP', 'kaito.nakamura@example.com', '7001-1021', NOW(), NOW()),
(22, UUID(), 'ALU022', 'Elizabeth Davis', 'Dallas, US', 'elizabeth.davis@example.com', '7001-1022', NOW(), NOW()),
(23, UUID(), 'ALU023', 'Thomas Petit', 'Lyon, France', 'thomas.petit@example.com', '7001-1023', NOW(), NOW()),
(24, UUID(), 'ALU024', 'Sofía Romero', 'Buenos Aires, Argentina', 'sofia.romero@example.com', '7001-1024', NOW(), NOW()),
(25, UUID(), 'ALU025', 'Ren Kobayashi', 'Fukuoka, JP', 'ren.kobayashi@example.com', '7001-1025', NOW(), NOW()),
(26, UUID(), 'ALU026', 'David Wilson', 'Miami, US', 'david.wilson@example.com', '7001-1026', NOW(), NOW()),
(27, UUID(), 'ALU027', 'Andreas Fischer', 'Cologne, Germany', 'andreas.fischer@example.com', '7001-1027', NOW(), NOW()),
(28, UUID(), 'ALU028', 'Valentina Ruiz', 'Santiago, Chile', 'valentina.ruiz@example.com', '7001-1028', NOW(), NOW()),
(29, UUID(), 'ALU029', 'Sora Kato', 'Kawasaki, JP', 'sora.kato@example.com', '7001-1029', NOW(), NOW()),
(30, UUID(), 'ALU030', 'Linda Taylor', 'Seattle, US', 'linda.taylor@example.com', '7001-1030', NOW(), NOW()),
(31, UUID(), 'ALU031', 'Nicolas Simon', 'Nice, France', 'nicolas.simon@example.com', '7001-1031', NOW(), NOW()),
(32, UUID(), 'ALU032', 'Gabriel Silva', 'Sao Paulo, Brazil', 'gabriel.silva@example.com', '7001-1032', NOW(), NOW()),
(33, UUID(), 'ALU033', 'Yuma Yoshida', 'Saitama, JP', 'yuma.yoshida@example.com', '7001-1033', NOW(), NOW()),
(34, UUID(), 'ALU034', 'Richard Moore', 'Atlanta, US', 'richard.moore@example.com', '7001-1034', NOW(), NOW()),
(35, UUID(), 'ALU035', 'Markus Weber', 'Frankfurt, Germany', 'markus.weber@example.com', '7001-1035', NOW(), NOW()),
(36, UUID(), 'ALU036', 'Camila Torres', 'Quito, Ecuador', 'camila.torres@example.com', '7001-1036', NOW(), NOW()),
(37, UUID(), 'ALU037', 'Itsuki Yamada', 'Hiroshima, JP', 'itsuki.yamada@example.com', '7001-1037', NOW(), NOW()),
(38, UUID(), 'ALU038', 'Susan Anderson', 'Denver, US', 'susan.anderson@example.com', '7001-1038', NOW(), NOW()),
(39, UUID(), 'ALU039', 'Emma Michel', 'Nantes, France', 'emma.michel@example.com', '7001-1039', NOW(), NOW()),
(40, UUID(), 'ALU040', 'Mateo Vargas', 'Asuncion, Paraguay', 'mateo.vargas@example.com', '7001-1040', NOW(), NOW()),
(41, UUID(), 'ALU041', 'Riku Sasaki', 'Sendai, JP', 'riku.sasaki@example.com', '7001-1041', NOW(), NOW()),
(42, UUID(), 'ALU042', 'Joseph Thomas', 'Las Vegas, US', 'joseph.thomas@example.com', '7001-1042', NOW(), NOW()),
(43, UUID(), 'ALU043', 'Jan Becker', 'Stuttgart, Germany', 'jan.becker@example.com', '7001-1043', NOW(), NOW()),
(44, UUID(), 'ALU044', 'Luciana Mendoza', 'Montevideo, Uruguay', 'luciana.mendoza@example.com', '7001-1044', NOW(), NOW()),
(45, UUID(), 'ALU045', 'Minato Yamaguchi', 'Kitakyushu, JP', 'minato.yamaguchi@example.com', '7001-1045', NOW(), NOW()),
(46, UUID(), 'ALU046', 'Dorothy Jackson', 'Phoenix, US', 'dorothy.jackson@example.com', '7001-1046', NOW(), NOW()),
(47, UUID(), 'ALU047', 'Lucas Bernard', 'Strasbourg, France', 'lucas.bernard@example.com', '7001-1047', NOW(), NOW()),
(48, UUID(), 'ALU048', 'Sebastian Ortiz', 'Guatemala City, GT', 'sebastian.ortiz@example.com', '7001-1048', NOW(), NOW()),
(49, UUID(), 'ALU049', 'Hinata Matsumoto', 'Chiba, JP', 'hinata.matsumoto@example.com', '7001-1049', NOW(), NOW()),
(50, UUID(), 'ALU050', 'Charles White', 'Portland, US', 'charles.white@example.com', '7001-1050', NOW(), NOW()),
(51, UUID(), 'ALU051', 'Julian Hoffman', 'Düsseldorf, Germany', 'julian.hoffman@example.com', '7001-1051', NOW(), NOW()),
(52, UUID(), 'ALU052', 'Isabella López', 'San José, Costa Rica', 'isabella.lopez@example.com', '7001-1052', NOW(), NOW()),
(53, UUID(), 'ALU053', 'Asahi Inoue', 'Sakai, JP', 'asahi.inoue@example.com', '7001-1053', NOW(), NOW()),
(54, UUID(), 'ALU054', 'Paul Harris', 'Nashville, US', 'paul.harris@example.com', '7001-1054', NOW(), NOW()),
(55, UUID(), 'ALU055', 'Hugo Robert', 'Montpellier, France', 'hugo.robert@example.com', '7001-1055', NOW(), NOW()),
(56, UUID(), 'ALU056', 'Daniela Ríos', 'Panama City, PA', 'daniela.rios@example.com', '7001-1056', NOW(), NOW()),
(57, UUID(), 'ALU057', 'Yuito Kimura', 'Niigata, JP', 'yuito.kimura@example.com', '7001-1057', NOW(), NOW()),
(58, UUID(), 'ALU058', 'Mark Martin', 'New Orleans, US', 'mark.martin@example.com', '7001-1058', NOW(), NOW()),
(59, UUID(), 'ALU059', 'Alexander Schäfer', 'Leipzig, Germany', 'alexander.schaefer@example.com', '7001-1059', NOW(), NOW()),
(60, UUID(), 'ALU060', 'Diego Flores', 'Tegucigalpa, Honduras', 'diego.flores@example.com', '7001-1060', NOW(), NOW()),
(61, UUID(), 'ALU061', 'Shoma Hayashi', 'Hamamatsu, JP', 'shoma.hayashi@example.com', '7001-1061', NOW(), NOW()),
(62, UUID(), 'ALU062', 'William Thompson', 'Cleveland, US', 'william.thompson@example.com', '7001-1062', NOW(), NOW()),
(63, UUID(), 'ALU063', 'Louis Richard', 'Bordeaux, France', 'louis.richard@example.com', '7001-1063', NOW(), NOW()),
(64, UUID(), 'ALU064', 'Elena Morales', 'San Salvador, SV', 'elena.morales@example.com', '7001-1064', NOW(), NOW()),
(65, UUID(), 'ALU065', 'Eita Shimizu', 'Kumamoto, JP', 'eita.shimizu@example.com', '7001-1065', NOW(), NOW()),
(66, UUID(), 'ALU066', 'George Garcia', 'Memphis, US', 'george.garcia@example.com', '7001-1066', NOW(), NOW()),
(67, UUID(), 'ALU067', 'Matthias Koch', 'Essen, Germany', 'matthias.koch@example.com', '7001-1067', NOW(), NOW()),
(68, UUID(), 'ALU068', 'Paola Herrera', 'Managua, Nicaragua', 'paola.herrera@example.com', '7001-1068', NOW(), NOW()),
(69, UUID(), 'ALU069', 'Haru Abe', 'Sagamihara, JP', 'haru.abe@example.com', '7001-1069', NOW(), NOW()),
(70, UUID(), 'ALU070', 'Steven Young', 'Salt Lake City, US', 'steven.young@example.com', '7001-1070', NOW(), NOW()),
(71, UUID(), 'ALU071', 'Arthur Durand', 'Lille, France', 'arthur.durand@example.com', '7001-1071', NOW(), NOW()),
(72, UUID(), 'ALU072', 'Andrés Jiménez', 'Santo Domingo, DO', 'andres.jimenez@example.com', '7001-1072', NOW(), NOW()),
(73, UUID(), 'ALU073', 'Sota Ikeda', 'Utsunomiya, JP', 'sota.ikeda@example.com', '7001-1073', NOW(), NOW()),
(74, UUID(), 'ALU074', 'Edward Lewis', 'Minneapolis, US', 'edward.lewis@example.com', '7001-1074', NOW(), NOW()),
(75, UUID(), 'ALU075', 'Christian Richter', 'Dortmund, Germany', 'christian.richter@example.com', '7001-1075', NOW(), NOW()),
(76, UUID(), 'ALU076', 'Adriana Solís', 'San Juan, Puerto Rico', 'adriana.solis@example.com', '7001-1076', NOW(), NOW()),
(77, UUID(), 'ALU077', 'Kenshin Hashimoto', 'Matsuyama, JP', 'kenshin.hashimoto@example.com', '7001-1077', NOW(), NOW()),
(78, UUID(), 'ALU078', 'Frank Walker', 'Austin, US', 'frank.walker@example.com', '7001-1078', NOW(), NOW()),
(79, UUID(), 'ALU079', 'Gabriel Lefebvre', 'Rennes, France', 'gabriel.lefebvre@example.com', '7001-1079', NOW(), NOW()),
(80, UUID(), 'ALU080', 'Ricardo Navarro', 'Caracas, Venezuela', 'ricardo.navarro@example.com', '7001-1080', NOW(), NOW()),
(81, UUID(), 'ALU081', 'Mizuki Yamashita', 'Kochi, JP', 'mizuki.yamashita@example.com', '7001-1081', NOW(), NOW()),
(82, UUID(), 'ALU082', 'Larry Robinson', 'San Antonio, US', 'larry.robinson@example.com', '7001-1082', NOW(), NOW()),
(83, UUID(), 'ALU083', 'Leon Bauer', 'Bremen, Germany', 'leon.bauer@example.com', '7001-1083', NOW(), NOW()),
(84, UUID(), 'ALU084', 'Victoria Peña', 'La Paz, Bolivia', 'victoria.pena@example.com', '7001-1084', NOW(), NOW()),
(85, UUID(), 'ALU085', 'Hayato Mori', 'Nara, JP', 'hayato.mori@example.com', '7001-1085', NOW(), NOW()),
(86, UUID(), 'ALU086', 'Scott Hall', 'Detroit, US', 'scott.hall@example.com', '7001-1086', NOW(), NOW()),
(87, UUID(), 'ALU087', 'Théo Moreau', 'Reims, France', 'theo.moreau@example.com', '7001-1087', NOW(), NOW()),
(88, UUID(), 'ALU088', 'Fernando Blanco', 'Guadalajara, Mexico', 'fernando.blanco@example.com', '7001-1088', NOW(), NOW()),
(89, UUID(), 'ALU089', 'Tsubasa Maeda', 'Funabashi, JP', 'tsubasa.maeda@example.com', '7001-1089', NOW(), NOW()),
(90, UUID(), 'ALU090', 'Raymond Allen', 'Columbus, US', 'raymond.allen@example.com', '7001-1090', NOW(), NOW()),
(91, UUID(), 'ALU091', 'Maximilian Wolf', 'Hannover, Germany', 'maximilian.wolf@example.com', '7001-1091', NOW(), NOW()),
(92, UUID(), 'ALU092', 'Patricia Delgado', 'Havana, Cuba', 'patricia.delgado@example.com', '7001-1092', NOW(), NOW()),
(93, UUID(), 'ALU093', 'Ren Osawa', 'Nagano, JP', 'ren.osawa@example.com', '7001-1093', NOW(), NOW()),
(94, UUID(), 'ALU094', 'Joshua King', 'Charlotte, US', 'joshua.king@example.com', '7001-1094', NOW(), NOW()),
(95, UUID(), 'ALU095', 'Antoine Laurent', 'Toulon, France', 'antoine.laurent@example.com', '7001-1095', NOW(), NOW()),
(96, UUID(), 'ALU096', 'Alejandra Campos', 'Queretaro, Mexico', 'alejandra.campos@example.com', '7001-1096', NOW(), NOW()),
(97, UUID(), 'ALU097', 'Kaede Ishikawa', 'Toyama, JP', 'kaede.ishikawa@example.com', '7001-1097', NOW(), NOW()),
(98, UUID(), 'ALU098', 'Gregory Wright', 'Indianapolis, US', 'gregory.wright@example.com', '7001-1098', NOW(), NOW()),
(99, UUID(), 'ALU099', 'Niklas Neumann', 'Dresden, Germany', 'niklas.neumann@example.com', '7001-1099', NOW(), NOW()),
(100, UUID(), 'ALU100', 'Beatriz Soto', 'San Salvador, SV', 'beatriz.soto@example.com', '7001-1100', NOW(), NOW());

-- 2. POBLAMIENTO DE LA TABLA: docentes (100 registros)
INSERT INTO docentes (id, idDocente, codigo, nombre, direccion, email, telefono, escalafon, created_at, updated_at) VALUES
(1, UUID(), 'DOC001', 'Dr. Kenichi Ohmae', 'Tokyo Tech District, JP', 'kenichi.ohmae@univ.edu', '6001-2001', 'Categoría I - Investigador', NOW(), NOW()),
(2, UUID(), 'DOC002', 'Prof. Alan Turing', 'Cambridge St, UK', 'alan.turing@univ.edu', '6001-2002', 'Categoría IV - Senior', NOW(), NOW()),
(3, UUID(), 'DOC003', 'Ing. Dieter Zetsche', 'Stuttgart IT Hub, Germany', 'dieter.zetsche@univ.edu', '6001-2003', 'Categoría III - Titular', NOW(), NOW()),
(4, UUID(), 'DOC004', 'Msc. Roberto Canessa', 'Montevideo Educativa, Uruguay', 'roberto.canessa@univ.edu', '6001-2004', 'Categoría II - Asociado', NOW(), NOW()),
-- Agregando más docentes con nombres multiculturales para llegar a 100
(5, UUID(), 'DOC005', 'Yuji Ide', 'Yamanashi, JP', 'yuji.ide@univ.edu', '6001-2005', 'Categoría I', NOW(), NOW()),
(6, UUID(), 'DOC006', 'Barbara Liskov', 'MIT Plaza, US', 'barbara.liskov@univ.edu', '6001-2006', 'Categoría IV', NOW(), NOW()),
(7, UUID(), 'DOC007', 'Jean Tirole', 'Toulouse School, France', 'jean.tirole@univ.edu', '6001-2007', 'Categoría IV', NOW(), NOW()),
(8, UUID(), 'DOC008', 'Linus Torvalds', 'Helsinki Tech, Finland', 'linus.torvalds@univ.edu', '6001-2008', 'Categoría IV', NOW(), NOW()),
-- ... (Acortando para el bloque, pero generaré los lotes necesarios)
(9, UUID(), 'DOC009', 'Ken Thompson', 'Bell Labs, US', 'ken.thompson@univ.edu', '6001-2009', 'Categoría IV', NOW(), NOW()),
(10, UUID(), 'DOC010', 'Guido van Rossum', 'Haarlem, Netherlands', 'guido.rossum@univ.edu', '6001-2010', 'Categoría III', NOW(), NOW());
-- Se insertarán los restantes en lotes para completar los 100.
-- [CONTINUACIÓN DE DOCENTES EN LOTES]
INSERT INTO docentes (id, idDocente, codigo, nombre, direccion, email, telefono, escalafon, created_at, updated_at) VALUES
(11, UUID(), 'DOC011', 'Tim Berners-Lee', 'London, UK', 'tim.lee@univ.edu', '6001-2011', 'Categoría IV', NOW(), NOW()),
(12, UUID(), 'DOC012', 'Grace Hopper', 'Arlington, US', 'grace.hopper@univ.edu', '6001-2012', 'Categoría IV', NOW(), NOW()),
(13, UUID(), 'DOC013', 'Bjarne Stroustrup', 'Aarhus, Denmark', 'bjarne.s@univ.edu', '6001-2013', 'Categoría IV', NOW(), NOW()),
(14, UUID(), 'DOC014', 'Ada Lovelace', 'Westminster, UK', 'ada.l@univ.edu', '6001-2014', 'Categoría IV', NOW(), NOW()),
(15, UUID(), 'DOC015', 'James Gosling', 'Calgary, Canada', 'james.g@univ.edu', '6001-2015', 'Categoría IV', NOW(), NOW()),
(16, UUID(), 'DOC016', 'Don Knuth', 'Stanford, US', 'don.k@univ.edu', '6001-2016', 'Categoría IV', NOW(), NOW()),
(17, UUID(), 'DOC017', 'Dennis Ritchie', 'Bronxville, US', 'dennis.r@univ.edu', '6001-2017', 'Categoría IV', NOW(), NOW()),
(18, UUID(), 'DOC018', 'Margaret Hamilton', 'Paoli, US', 'margaret.h@univ.edu', '6001-2018', 'Categoría IV', NOW(), NOW()),
(19, UUID(), 'DOC019', 'Vint Cerf', 'New Haven, US', 'vint.c@univ.edu', '6001-2019', 'Categoría IV', NOW(), NOW()),
(20, UUID(), 'DOC020', 'Bob Kahn', 'Brooklyn, US', 'bob.k@univ.edu', '6001-2020', 'Categoría IV', NOW(), NOW()),
(21, UUID(), 'DOC021', 'Yoshua Bengio', 'Paris, France', 'yoshua.b@univ.edu', '6001-2021', 'Categoría III', NOW(), NOW()),
(22, UUID(), 'DOC022', 'Yann LeCun', 'Soisy-sous-Montmorency, France', 'yann.l@univ.edu', '6001-2022', 'Categoría III', NOW(), NOW()),
(23, UUID(), 'DOC023', 'Geoffrey Hinton', 'Wimbledon, UK', 'geoffrey.h@univ.edu', '6001-2023', 'Categoría III', NOW(), NOW()),
(24, UUID(), 'DOC024', 'Andrew Ng', 'London, UK', 'andrew.ng@univ.edu', '6001-2024', 'Categoría III', NOW(), NOW()),
(25, UUID(), 'DOC025', 'Fei-Fei Li', 'Beijing, China', 'feifei.li@univ.edu', '6001-2025', 'Categoría II', NOW(), NOW()),
(26, UUID(), 'DOC026', 'Demis Hassabis', 'London, UK', 'demis.h@univ.edu', '6001-2026', 'Categoría II', NOW(), NOW()),
(27, UUID(), 'DOC027', 'Ian Goodfellow', 'California, US', 'ian.g@univ.edu', '6001-2027', 'Categoría II', NOW(), NOW()),
(28, UUID(), 'DOC028', 'Andrej Karpathy', 'Bratislava, Slovakia', 'andrej.k@univ.edu', '6001-2028', 'Categoría II', NOW(), NOW()),
(29, UUID(), 'DOC029', 'Chris Lattner', 'California, US', 'chris.l@univ.edu', '6001-2029', 'Categoría II', NOW(), NOW()),
(30, UUID(), 'DOC030', 'Jeff Dean', 'Hawaii, US', 'jeff.d@univ.edu', '6001-2030', 'Categoría IV', NOW(), NOW()),
(31, UUID(), 'DOC031', 'Sanjay Ghemawat', 'Lafayette, US', 'sanjay.g@univ.edu', '6001-2031', 'Categoría IV', NOW(), NOW()),
(32, UUID(), 'DOC032', 'Rob Pike', 'Canada', 'rob.p@univ.edu', '6001-2032', 'Categoría IV', NOW(), NOW()),
(33, UUID(), 'DOC033', 'Bill Joy', 'Farmington Hill, US', 'bill.j@univ.edu', '6001-2033', 'Categoría IV', NOW(), NOW()),
(34, UUID(), 'DOC034', 'John Carmack', 'Roeland Park, US', 'john.c@univ.edu', '6001-2034', 'Categoría III', NOW(), NOW()),
(35, UUID(), 'DOC035', 'Fabrice Bellard', 'Grenoble, France', 'fabrice.b@univ.edu', '6001-2035', 'Categoría III', NOW(), NOW()),
(36, UUID(), 'DOC036', 'Anders Hejlsberg', 'Copenhagen, Denmark', 'anders.h@univ.edu', '6001-2036', 'Categoría IV', NOW(), NOW()),
(37, UUID(), 'DOC037', 'Niklaus Wirth', 'Winterthur, Switzerland', 'niklaus.w@univ.edu', '6001-2037', 'Categoría IV', NOW(), NOW()),
(38, UUID(), 'DOC038', 'Butler Lampson', 'Washington, US', 'butler.l@univ.edu', '6001-2038', 'Categoría IV', NOW(), NOW()),
(39, UUID(), 'DOC039', 'Leslie Lamport', 'New York, US', 'leslie.l@univ.edu', '6001-2039', 'Categoría IV', NOW(), NOW()),
(40, UUID(), 'DOC040', 'Barbara Grosz', 'Philadelphia, US', 'barbara.g@univ.edu', '6001-2040', 'Categoría IV', NOW(), NOW()),
(41, UUID(), 'DOC041', 'Shigeru Miyamoto', 'Kyoto, JP', 'shigeru.m@univ.edu', '6001-2041', 'Categoría IV', NOW(), NOW()),
(42, UUID(), 'DOC042', 'Hideo Kojima', 'Setagaya, JP', 'hideo.k@univ.edu', '6001-2042', 'Categoría III', NOW(), NOW()),
(43, UUID(), 'DOC043', 'Masahiro Sakurai', 'Tokyo, JP', 'masahiro.s@univ.edu', '6001-2043', 'Categoría II', NOW(), NOW()),
(44, UUID(), 'DOC044', 'Yuji Horii', 'Sumoto, JP', 'yuji.h@univ.edu', '6001-2044', 'Categoría III', NOW(), NOW()),
(45, UUID(), 'DOC045', 'Toby Fox', 'Manchester, US', 'toby.f@univ.edu', '6001-2045', 'Categoría I', NOW(), NOW()),
(46, UUID(), 'DOC046', 'Sid Meier', 'Sarnia, Canada', 'sid.m@univ.edu', '6001-2046', 'Categoría IV', NOW(), NOW()),
(47, UUID(), 'DOC047', 'Will Wright', 'Atlanta, US', 'will.w@univ.edu', '6001-2047', 'Categoría IV', NOW(), NOW()),
(48, UUID(), 'DOC048', 'Markus Persson', 'Stockholm, Sweden', 'markus.p@univ.edu', '6001-2048', 'Categoría I', NOW(), NOW()),
(49, UUID(), 'DOC049', 'Casey Rodarmor', 'California, US', 'casey.r@univ.edu', '6001-2049', 'Categoría I', NOW(), NOW()),
(50, UUID(), 'DOC050', 'Vitalik Buterin', 'Kolomna, Russia', 'vitalik.b@univ.edu', '6001-2050', 'Categoría II', NOW(), NOW()),
(51, UUID(), 'DOC051', 'Gavin Wood', 'Lancaster, UK', 'gavin.w@univ.edu', '6001-2051', 'Categoría II', NOW(), NOW()),
(52, UUID(), 'DOC052', 'Charles Hoskinson', 'Hawaii, US', 'charles.h@univ.edu', '6001-2052', 'Categoría III', NOW(), NOW()),
(53, UUID(), 'DOC053', 'Silvio Micali', 'Palermo, Italy', 'silvio.m@univ.edu', '6001-2053', 'Categoría IV', NOW(), NOW()),
(54, UUID(), 'DOC054', 'Whitfield Diffie', 'Washington, US', 'whitfield.d@univ.edu', '6001-2054', 'Categoría IV', NOW(), NOW()),
(55, UUID(), 'DOC055', 'Martin Hellman', 'New York, US', 'martin.h@univ.edu', '6001-2055', 'Categoría IV', NOW(), NOW()),
(56, UUID(), 'DOC056', 'Ralph Merkle', 'Berkeley, US', 'ralph.m@univ.edu', '6001-2056', 'Categoría III', NOW(), NOW()),
(57, UUID(), 'DOC057', 'David Chaum', 'California, US', 'david.c@univ.edu', '6001-2057', 'Categoría III', NOW(), NOW()),
(58, UUID(), 'DOC058', 'Adam Back', 'London, UK', 'adam.b@univ.edu', '6001-2058', 'Categoría II', NOW(), NOW()),
(59, UUID(), 'DOC059', 'Nick Szabo', 'US', 'nick.s@univ.edu', '6001-2059', 'Categoría III', NOW(), NOW()),
(60, UUID(), 'DOC060', 'Hal Finney', 'California, US', 'hal.f@univ.edu', '6001-2060', 'Categoría IV', NOW(), NOW()),
(61, UUID(), 'DOC061', 'Wei Dai', 'US', 'wei.d@univ.edu', '6001-2061', 'Categoría II', NOW(), NOW()),
(62, UUID(), 'DOC062', 'Zooko Wilcox-O\'Hearn', 'Phoenix, US', 'zooko.w@univ.edu', '6001-2062', 'Categoría II', NOW(), NOW()),
(63, UUID(), 'DOC063', 'Bram Cohen', 'Miami, US', 'bram.c@univ.edu', '6001-2063', 'Categoría III', NOW(), NOW()),
(64, UUID(), 'DOC064', 'Julian Assange', 'Townsville, Australia', 'julian.a@univ.edu', '6001-2064', 'Categoría I', NOW(), NOW()),
(65, UUID(), 'DOC065', 'Aaron Swartz', 'Chicago, US', 'aaron.s@univ.edu', '6001-2065', 'Categoría I', NOW(), NOW()),
(66, UUID(), 'DOC066', 'Lawrence Lessig', 'South Dakota, US', 'lawrence.l@univ.edu', '6001-2066', 'Categoría IV', NOW(), NOW()),
(67, UUID(), 'DOC067', 'Richard Stallman', 'New York, US', 'richard.s@univ.edu', '6001-2067', 'Categoría IV', NOW(), NOW()),
(68, UUID(), 'DOC068', 'Eric S. Raymond', 'Boston, US', 'eric.r@univ.edu', '6001-2068', 'Categoría III', NOW(), NOW()),
(69, UUID(), 'DOC069', 'Bruce Perens', 'Washington, US', 'bruce.p@univ.edu', '6001-2069', 'Categoría III', NOW(), NOW()),
(70, UUID(), 'DOC070', 'Marc Andreessen', 'Cedar Falls, US', 'marc.a@univ.edu', '6001-2070', 'Categoría IV', NOW(), NOW()),
(71, UUID(), 'DOC071', 'Brendan Eich', 'Pittsburgh, US', 'brendan.e@univ.edu', '6001-2071', 'Categoría III', NOW(), NOW()),
(72, UUID(), 'DOC072', 'Rasmus Lerdorf', 'Qeqertarsuaq, Greenland', 'rasmus.l@univ.edu', '6001-2072', 'Categoría III', NOW(), NOW()),
(73, UUID(), 'DOC073', 'Larry Wall', 'Los Angeles, US', 'larry.w@univ.edu', '6001-2073', 'Categoría IV', NOW(), NOW()),
(74, UUID(), 'DOC074', 'Yukihiro Matsumoto', 'Osaka, JP', 'matz.m@univ.edu', '6001-2074', 'Categoría III', NOW(), NOW()),
(75, UUID(), 'DOC075', 'David Heinemeier Hansson', 'Copenhagen, Denmark', 'dhh.h@univ.edu', '6001-2075', 'Categoría II', NOW(), NOW()),
(76, UUID(), 'DOC076', 'Taylor Otwell', 'Arkansas, US', 'taylor.o@univ.edu', '6001-2076', 'Categoría II', NOW(), NOW()),
(77, UUID(), 'DOC077', 'Evan You', 'Wuxi, China', 'evan.y@univ.edu', '6001-2077', 'Categoría II', NOW(), NOW()),
(78, UUID(), 'DOC078', 'Jordan Walke', 'US', 'jordan.w@univ.edu', '6001-2078', 'Categoría II', NOW(), NOW()),
(79, UUID(), 'DOC079', 'Rich Harris', 'UK', 'rich.h@univ.edu', '6001-2079', 'Categoría I', NOW(), NOW()),
(80, UUID(), 'DOC080', 'Ryan Dahl', 'US', 'ryan.d@univ.edu', '6001-2080', 'Categoría II', NOW(), NOW()),
(81, UUID(), 'DOC081', 'Isaac Schlueter', 'US', 'isaac.s@univ.edu', '6001-2081', 'Categoría II', NOW(), NOW()),
(82, UUID(), 'DOC082', 'Mike Bostock', 'US', 'mike.b@univ.edu', '6001-2082', 'Categoría III', NOW(), NOW()),
(83, UUID(), 'DOC083', 'Jeremy Ashkenas', 'US', 'jeremy.a@univ.edu', '6001-2083', 'Categoría II', NOW(), NOW()),
(84, UUID(), 'DOC084', 'John Resig', 'US', 'john.r@univ.edu', '6001-2084', 'Categoría III', NOW(), NOW()),
(85, UUID(), 'DOC085', 'Douglas Crockford', 'US', 'douglas.c@univ.edu', '6001-2085', 'Categoría IV', NOW(), NOW()),
(86, UUID(), 'DOC086', 'Kyle Simpson', 'US', 'kyle.s@univ.edu', '6001-2086', 'Categoría II', NOW(), NOW()),
(87, UUID(), 'DOC087', 'Addy Osmani', 'Ireland', 'addy.o@univ.edu', '6001-2087', 'Categoría II', NOW(), NOW()),
(88, UUID(), 'DOC088', 'Paul Irish', 'US', 'paul.i@univ.edu', '6001-2088', 'Categoría II', NOW(), NOW()),
(89, UUID(), 'DOC089', 'Jake Archibald', 'UK', 'jake.a@univ.edu', '6001-2089', 'Categoría II', NOW(), NOW()),
(90, UUID(), 'DOC090', 'Una Kravets', 'US', 'una.k@univ.edu', '6001-2090', 'Categoría II', NOW(), NOW()),
(91, UUID(), 'DOC091', 'Chris Coyier', 'US', 'chris.c@univ.edu', '6001-2091', 'Categoría II', NOW(), NOW()),
(92, UUID(), 'DOC092', 'Jen Simmons', 'US', 'jen.s@univ.edu', '6001-2092', 'Categoría III', NOW(), NOW()),
(93, UUID(), 'DOC093', 'Rachel Andrew', 'UK', 'rachel.a@univ.edu', '6001-2093', 'Categoría III', NOW(), NOW()),
(94, UUID(), 'DOC094', 'Sara Soueidan', 'Lebanon', 'sara.s@univ.edu', '6001-2094', 'Categoría II', NOW(), NOW()),
(95, UUID(), 'DOC095', 'Lea Verou', 'Greece', 'lea.v@univ.edu', '6001-2095', 'Categoría II', NOW(), NOW()),
(96, UUID(), 'DOC096', 'Vitaly Friedman', 'Russia', 'vitaly.f@univ.edu', '6001-2096', 'Categoría II', NOW(), NOW()),
(97, UUID(), 'DOC097', 'Smashing Mag', 'Germany', 'smashing.m@univ.edu', '6001-2097', 'Categoría IV', NOW(), NOW()),
(98, UUID(), 'DOC098', 'Cassidy Williams', 'US', 'cassidy.w@univ.edu', '6001-2098', 'Categoría I', NOW(), NOW()),
(99, UUID(), 'DOC099', 'Kent C. Dodds', 'US', 'kent.d@univ.edu', '6001-2099', 'Categoría II', NOW(), NOW()),
(100, UUID(), 'DOC100', 'Quincy Larson', 'US', 'quincy.l@univ.edu', '6001-2100', 'Categoría II', NOW(), NOW());

-- 3. POBLAMIENTO DE LA TABLA: materias (100 registros)
-- Áreas: Ingeniería de Software, Frontend, Backend, Redes, AI, BD, etc.
INSERT INTO materias (id, idMateria, codigo, nombre, uv, created_at, updated_at) VALUES
(1, UUID(), 'SWE101', 'Arquitectura de Software I', 4, NOW(), NOW()),
(2, UUID(), 'WEB102', 'Desarrollo Frontend con Vue.js', 3, NOW(), NOW()),
(3, UUID(), 'BCK103', 'Backend PHP con Laravel Avanzado', 4, NOW(), NOW()),
(4, UUID(), 'NET104', 'Redes de Datos y Enrutamiento', 4, NOW(), NOW()),
(5, UUID(), 'IAI105', 'Inteligencia Artificial I', 4, NOW(), NOW()),
(6, UUID(), 'DBM106', 'Bases de Datos Relacionales', 4, NOW(), NOW()),
(7, UUID(), 'SEC107', 'Ciberseguridad y Pentesting', 4, NOW(), NOW()),
(8, UUID(), 'MOB108', 'Desarrollo Mobile con React Native', 3, NOW(), NOW()),
(9, UUID(), 'OPS109', 'Sistemas Operativos II', 4, NOW(), NOW()),
(10, UUID(), 'DAT110', 'Estructuras de Datos Avanzadas', 4, NOW(), NOW()),
(11, UUID(), 'SWE201', 'Arquitectura de Software II', 4, NOW(), NOW()),
(12, UUID(), 'WEB202', 'Desarrollo Frontend con React', 3, NOW(), NOW()),
(13, UUID(), 'BCK203', 'Backend Node.js y Express', 4, NOW(), NOW()),
(14, UUID(), 'NET204', 'Seguridad en Redes Inalámbricas', 4, NOW(), NOW()),
(15, UUID(), 'IAI205', 'Machine Learning con Python', 4, NOW(), NOW()),
(16, UUID(), 'DBM206', 'Administración de MySQL Server', 4, NOW(), NOW()),
(17, UUID(), 'SEC207', 'Análisis Forense Digital', 4, NOW(), NOW()),
(18, UUID(), 'MOB208', 'Desarrollo Mobile con Flutter', 3, NOW(), NOW()),
(19, UUID(), 'OPS209', 'Virtualización y Contenedores', 4, NOW(), NOW()),
(20, UUID(), 'DAT210', 'Algoritmos de Optimización', 4, NOW(), NOW()),
(21, UUID(), 'BCK301', 'Microservicios con Spring Boot', 4, NOW(), NOW()),
(22, UUID(), 'UIX302', 'UI/UX Design para Ingenieros', 3, NOW(), NOW()),
(23, UUID(), 'BCK303', 'API Design y Documentación', 4, NOW(), NOW()),
(24, UUID(), 'IOT304', 'Internet de las Cosas (IoT)', 4, NOW(), NOW()),
(25, UUID(), 'IAI305', 'Deep Learning y Redes Neuronales', 4, NOW(), NOW()),
(26, UUID(), 'DBM306', 'Bases de Datos NoSQL (MongoDB)', 4, NOW(), NOW()),
(27, UUID(), 'AUD307', 'Auditoría de Sistemas I', 4, NOW(), NOW()),
(28, UUID(), 'GMD308', 'Desarrollo de Videojuegos I', 3, NOW(), NOW()),
(29, UUID(), 'CLD309', 'Cloud Computing con AWS', 4, NOW(), NOW()),
(30, UUID(), 'CMP310', 'Compiladores e Intérpretes', 4, NOW(), NOW()),
(31, UUID(), 'SWE401', 'Patrones de Diseño de Software', 4, NOW(), NOW()),
(32, UUID(), 'TQA402', 'Testing y QA Automatizado', 3, NOW(), NOW()),
(33, UUID(), 'DVO403', 'DevOps e Integración Continua', 4, NOW(), NOW()),
(34, UUID(), 'CLD404', 'Computación en la Niebla', 4, NOW(), NOW()),
(35, UUID(), 'IAI405', 'Visión por Computadora', 4, NOW(), NOW()),
(36, UUID(), 'DAT406', 'Data Warehousing y ETL', 4, NOW(), NOW()),
(37, UUID(), 'ETH407', 'Ética y Legislación Informática', 3, NOW(), NOW()),
(38, UUID(), 'XRX408', 'Realidad Aumentada y Virtual', 3, NOW(), NOW()),
(39, UUID(), 'CLD409', 'Serverless Computing', 4, NOW(), NOW()),
(40, UUID(), 'OPS410', 'Sistemas Distribuidos', 4, NOW(), NOW()),
(41, UUID(), 'MTH501', 'Metodologías Ágiles (Scrum/Kanban)', 3, NOW(), NOW()),
(42, UUID(), 'MKT502', 'SEO y Posicionamiento Web', 3, NOW(), NOW()),
(43, UUID(), 'BCK503', 'Go Programming para Backend', 4, NOW(), NOW()),
(44, UUID(), 'BCN504', 'Blockchain y Smart Contracts', 4, NOW(), NOW()),
(45, UUID(), 'IAI505', 'NLP - Procesamiento Lenguaje Natural', 4, NOW(), NOW()),
(46, UUID(), 'DAT506', 'Big Data con Apache Spark', 4, NOW(), NOW()),
(47, UUID(), 'MGM507', 'Gestión de Proyectos Tecnológicos', 4, NOW(), NOW()),
(48, UUID(), 'GMD508', 'Gráficos por Computadora 3D', 3, NOW(), NOW()),
(49, UUID(), 'OPS509', 'Site Reliability Engineering (SRE)', 4, NOW(), NOW()),
(50, UUID(), 'OPS510', 'Sistemas de Tiempo Real', 4, NOW(), NOW()),
(51, UUID(), 'SWE601', 'Diseño de Sistemas Tolerantes a Fallos', 4, NOW(), NOW()),
(52, UUID(), 'WEB602', 'Web Performance Optimization', 3, NOW(), NOW()),
(53, UUID(), 'BCK603', 'Ruby on Rails para Startups', 4, NOW(), NOW()),
(54, UUID(), 'SEC604', 'Criptografía Simétrica y Asimétrica', 4, NOW(), NOW()),
(55, UUID(), 'IAI605', 'Reinforcement Learning', 4, NOW(), NOW()),
(56, UUID(), 'DBM606', 'SQL Server Avanzado y T-SQL', 4, NOW(), NOW()),
(57, UUID(), 'SEC607', 'Hacking Ético II', 4, NOW(), NOW()),
(58, UUID(), 'GMD608', 'Game Engine Design (Unity)', 3, NOW(), NOW()),
(59, UUID(), 'CLD609', 'Azure Cloud Fundamentals', 4, NOW(), NOW()),
(60, UUID(), 'THC610', 'Teoría de la Computación', 4, NOW(), NOW()),
(61, UUID(), 'PRG701', 'Principios de Programación Funcional', 4, NOW(), NOW()),
(62, UUID(), 'WEB702', 'E-Commerce y Pasarelas de Pago', 3, NOW(), NOW()),
(63, UUID(), 'SYS703', 'Rust para Programación de Sistemas', 4, NOW(), NOW()),
(64, UUID(), 'BCN704', 'Ethereum Development', 4, NOW(), NOW()),
(65, UUID(), 'IAI705', 'Data Mining e IA', 4, NOW(), NOW()),
(66, UUID(), 'DAT706', 'Hadoop y Ecosistema Big Data', 4, NOW(), NOW()),
(67, UUID(), 'LDW707', 'Liderazgo en Equipos de Devs', 3, NOW(), NOW()),
(68, UUID(), 'GMD708', 'Animación 2D/3D Técnica', 3, NOW(), NOW()),
(69, UUID(), 'OPS709', 'Kubernetes Orchestration', 4, NOW(), NOW()),
(70, UUID(), 'NET710', 'Protocolos de Aplicación TCP/IP', 4, NOW(), NOW()),
(71, UUID(), 'SWE801', 'Refactoring de Código Legacy', 3, NOW(), NOW()),
(72, UUID(), 'MKT802', 'Marketing Digital para IT', 3, NOW(), NOW()),
(73, UUID(), 'SYS803', 'C++ Moderno (C++20)', 4, NOW(), NOW()),
(74, UUID(), 'BCN804', 'Web3 y Descentralización', 4, NOW(), NOW()),
(75, UUID(), 'IAI805', 'Chatbots e Interfaces Conversacionales', 4, NOW(), NOW()),
(76, UUID(), 'DAT806', 'Visualización de Datos con D3.js', 4, NOW(), NOW()),
(77, UUID(), 'MGM807', 'Gestión de Riesgos Informáticos', 3, NOW(), NOW()),
(78, UUID(), 'DAT808', 'Motores de Búsqueda (Elasticsearch)', 4, NOW(), NOW()),
(79, UUID(), 'CLD809', 'Infraestructura como Código (Terraform)', 4, NOW(), NOW()),
(80, UUID(), 'MAT810', 'Modelado y Simulación', 4, NOW(), NOW()),
(81, UUID(), 'SYS901', 'Programación Concurrente y Paralela', 4, NOW(), NOW()),
(82, UUID(), 'WEB902', 'Accesibilidad Web (A11y)', 3, NOW(), NOW()),
(83, UUID(), 'BCK903', 'Django y Python Backend', 4, NOW(), NOW()),
(84, UUID(), 'SEC904', 'Defensa en Profundidad (Blue Team)', 4, NOW(), NOW()),
(85, UUID(), 'IAI905', 'Sistemas Expertos', 4, NOW(), NOW()),
(86, UUID(), 'DBM906', 'Bases de Datos Grafos (Neo4j)', 4, NOW(), NOW()),
(87, UUID(), 'ENT907', 'Emprendimiento Tecnológico', 3, NOW(), NOW()),
(88, UUID(), 'XRX908', 'Realidad Mixta (HoloLens)', 3, NOW(), NOW()),
(89, UUID(), 'OPS909', 'Observabilidad y Monitoreo (Grafana)', 4, NOW(), NOW()),
(90, UUID(), 'MAT910', 'Teoría de Colas en Sistemas', 4, NOW(), NOW()),
(91, UUID(), 'TES001', 'Taller de Tesis Informática I', 4, NOW(), NOW()),
(92, UUID(), 'TES002', 'Taller de Tesis Informática II', 4, NOW(), NOW()),
(93, UUID(), 'BCK003', 'C# y .NET Core Avanzado', 4, NOW(), NOW()),
(94, UUID(), 'SEC004', 'Seguridad en el Lado del Cliente', 4, NOW(), NOW()),
(95, UUID(), 'ROB005', 'Robótica Industrial Aplicada', 4, NOW(), NOW()),
(96, UUID(), 'SEC006', 'Gestión de Identidades (IAM)', 4, NOW(), NOW()),
(97, UUID(), 'INN007', 'Innovación Tecnológica', 3, NOW(), NOW()),
(98, UUID(), 'LNC008', 'Low-Code/No-Code Platforms', 3, NOW(), NOW()),
(99, UUID(), 'DAT009', 'Análisis de Redes Sociales', 3, NOW(), NOW()),
(100, UUID(), 'PRO100', 'Proyecto Final de Carrera', 6, NOW(), NOW());

-- 4. POBLAMIENTO DE LA TABLA: matriculas (100 registros)
-- Relación 1:1 con Alumnos
INSERT INTO matriculas (id, idMatricula, idAlumno, ciclo, fecha, pago, created_at, updated_at)
SELECT id, UUID(), id, 'Ciclo 01-2026', CURDATE(), 'SÍ', NOW(), NOW()
FROM alumnos;

-- 5. POBLAMIENTO DE LA TABLA: inscripciones (100 registros)
-- Relación 1:1 con Alumnos y Materias (Secuencial para prueba)
INSERT INTO inscripciones (id, idInscripcion, idAlumno, idMateria, ciclo, fecha, created_at, updated_at)
SELECT id, UUID(), id, id, 'Ciclo 01-2026', CURDATE(), NOW(), NOW()
FROM alumnos;

-- Finalización de script
COMMIT;
